name: Android Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Grant Gradle permission
        run: chmod +x ThreeFingerShot/gradlew

      - name: Build Debug APK
        run: cd ThreeFingerShot && ./gradlew assembleDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ThreeFingerShot-APK
          path: ThreeFingerShot/app/build/outputs/apk/debug/app-debug.apk
